version: '{build}'
skip_non_tags: false
image: Visual Studio 2019
clone_folder: c:\projects\dss_python
environment:
  DSS_CAPI_TAG: 0.10.7
  DSS_CAPI_PATH: c:\projects\dss_capi
  ANACONDA_API_TOKEN: 
    secure: Pcm5IXFi4ZUsi1ue5QvPNASDo1Ns1REYbAwDJXRd3FRn2CfKbNPgnPda6fxoN6wG
  matrix:
    - CONDA_SUBDIR: win-32
    - CONDA_SUBDIR: win-64
    
build_script:
- cmd: call ci\build_appveyor.bat
    
test: off