version: '{build}'
skip_non_tags: false
image: Visual Studio 2019
clone_folder: c:\projects\dss_python
environment:
  DSS_CAPI_TAG: 0.10.7-1
  DSS_CAPI_PATH: c:\projects\dss_capi
  ANACONDA_API_TOKEN: 
    secure: tz1RWAAmcTidoLDrrIvt8jUxe5nvzgHsLexDXESWFka5Faw+q7oq2J8sifJLT41m
  matrix:
    - CONDA_SUBDIR: win-32
    - CONDA_SUBDIR: win-64
    
build_script:
- cmd: call ci\build_appveyor.bat
    
test: off